export const lessons = [
  {
    id: 1001,
    subject: "Math",
    location: "London",
    price: 100,
    spaces: 5,
    icon: "fas fa-calculator",
  },
  {
    id: 1002,
    subject: "Math",
    location: "Oxford",
    price: 110,
    spaces: 5,
    icon: "fas fa-calculator",
  },
  {
    id: 1003,
    subject: "English",
    location: "London",
    price: 115,
    spaces: 5,
    icon: "fas fa-pen-fancy",
  },
  {
    id: 1004,
    subject: "English",
    location: "York",
    price: 80,
    spaces: 5,
    icon: "fas fa-pen-fancy",
  },
  {
    id: 1005,
    subject: "Music",
    location: "Bristol",
    price: 90,
    spaces: 5,
    icon: "fas fa-music",
  },
  {
    id: 1006,
    subject: "Science",
    location: "Oxford",
    price: 120,
    spaces: 10,
    icon: "fas fa-flask",
  },
  {
    id: 1007,
    subject: "History",
    location: "Bristol",
    price: 95,
    spaces: 6,
    icon: "fas fa-book",
  },
  {
    id: 1008,
    subject: "Art",
    location: "Glasgow",
    price: 70,
    spaces: 8,
    icon: "fas fa-paint-brush",
  },
  {
    id: 1009,
    subject: "Art",
    location: "Liverpool",
    price: 85,
    spaces: 10,
    icon: "fas fa-paint-brush",
  },
  {
    id: 1010,
    subject: "Science",
    location: "Cambridge",
    price: 150,
    spaces: 11,
    icon: "fas fa-flask",
  },
  {
    id: 1011,
    subject: "Drama",
    location: "London",
    price: 110,
    spaces: 8,
    icon: "fas fa-theater-masks",
  },
  {
    id: 1012,
    subject: "French",
    location: "London",
    price: 130,
    spaces: 5,
    icon: "fas fa-globe-europe",
  },
];
